version: '3.9'
services:
  app:
    image: ecom-api
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3333:3000
 
  postgres:
    image: postgres:14-alpine
    ports:
      - 5423:5432
    volumes:
      - ~/apps/postgres:/var/libs/postgres/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=ecom
